#!/bin/bash

set -o pipefail
set -e

. scripts/common.sh

if type "docker-machine" 2>/dev/null; then
  proxy_host=$(docker-machine ip default)
else
  proxy_host='localhost'
fi

# build proxy base image
./scripts/build_proxy_base_image.sh $1
