package online.kheops.auth_server.event;

public enum MutationType {
    ADD_USER, ADD_ADMIN, REMOVE_USER, PROMOTE_ADMIN, DEMOTE_ADMIN,
    CREATE_ALBUM, LEAVE_ALBUM,
    IMPORT_STUDY, IMPORT_SERIES, REMOVE_STUDY, REMOVE_SERIES,
    EDIT_ALBUM, ADD_FAV, REMOVE_FAV,
    CREATE_REPORT_PROVIDER, EDIT_REPORT_PROVIDER, DELETE_REPORT_PROVIDER,
    CREATE_WEBHOOK, DELETE_WEBHOOK, EDIT_WEBHOOK, TRIGGER_WEBHOOK
}
