name: DICOMwebProxy Docker Image CI

on:
  create:
  push:
    paths:
    - 'DICOMwebProxy/**'
    - '.github/workflows/DICOMwebProxy_docker_build_push.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract branch name
        if: startsWith(github.ref , 'refs/heads/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
        
      - name: Extract tag name
        if: startsWith(github.ref , 'refs/tags/')
        shell: bash
        run: echo "docker_tag=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV        
        
      - name: Build and push
        uses: docker/build-push-action@v2.2.1
        with:
          context: ./DICOMwebProxy
          file: DICOMwebProxy/Dockerfile
          platforms: linux/amd64
          push: true
          tags: osirixfoundation/kheops-dicomweb-proxy:${{ env.docker_tag }}   
